/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddDescriptorsResponse model module.
 * @module model/AddDescriptorsResponse
 * @version 1.0.0
 */
class AddDescriptorsResponse {
    /**
     * Constructs a new <code>AddDescriptorsResponse</code>.
     * @alias module:model/AddDescriptorsResponse
     * @param message {String} 
     * @param time {Date} 
     * @param serviceIDs {Array.<String>} Service IDs (e.g. helloworld.Greeter) registered. Use DELETE /services/{serviceID} to remove.
     */
    constructor(message, time, serviceIDs) { 
        
        AddDescriptorsResponse.initialize(this, message, time, serviceIDs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, time, serviceIDs) { 
        obj['message'] = message;
        obj['time'] = time;
        obj['serviceIDs'] = serviceIDs;
    }

    /**
     * Constructs a <code>AddDescriptorsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddDescriptorsResponse} obj Optional instance to populate.
     * @return {module:model/AddDescriptorsResponse} The populated <code>AddDescriptorsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddDescriptorsResponse();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
            if (data.hasOwnProperty('serviceIDs')) {
                obj['serviceIDs'] = ApiClient.convertToType(data['serviceIDs'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddDescriptorsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddDescriptorsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddDescriptorsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['serviceIDs'])) {
            throw new Error("Expected the field `serviceIDs` to be an array in the JSON data but got " + data['serviceIDs']);
        }

        return true;
    }


}

AddDescriptorsResponse.RequiredProperties = ["message", "time", "serviceIDs"];

/**
 * @member {String} message
 */
AddDescriptorsResponse.prototype['message'] = undefined;

/**
 * @member {Date} time
 */
AddDescriptorsResponse.prototype['time'] = undefined;

/**
 * Service IDs (e.g. helloworld.Greeter) registered. Use DELETE /services/{serviceID} to remove.
 * @member {Array.<String>} serviceIDs
 */
AddDescriptorsResponse.prototype['serviceIDs'] = undefined;






export default AddDescriptorsResponse;

