/**
 * GripMock API Schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddStub200Response model module.
 * @module model/AddStub200Response
 * @version 2.4.0
 */
class AddStub200Response {
    /**
     * Constructs a new <code>AddStub200Response</code>.
     * @alias module:model/AddStub200Response
     * @param {(module:model/[String])} instance The actual instance to initialize AddStub200Response.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate array data type
            if (!Array.isArray(instance)) {
                throw new Error("Invalid data type. Expecting array. Input: " + instance);
            }
            // validate array of string
            for (const item of instance) {
                if (!(typeof item === 'number' && item % 1 === 0)) {
                    throw new Error("Invalid array items. Must be string. Input: " + instance);
                }
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into [String]
            errorMessages.push("Failed to construct [String]: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `AddStub200Response` with oneOf schemas [String]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `AddStub200Response` with oneOf schemas [String]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>AddStub200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddStub200Response} obj Optional instance to populate.
     * @return {module:model/AddStub200Response} The populated <code>AddStub200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        return new AddStub200Response(data);
    }

    /**
     * Gets the actual instance, which can be <code>[String]</code>.
     * @return {(module:model/[String])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>[String]</code>.
     * @param {(module:model/[String])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = AddStub200Response.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of AddStub200Response from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/AddStub200Response} An instance of AddStub200Response.
     */
    static fromJSON = function(json_string){
        return AddStub200Response.constructFromObject(JSON.parse(json_string));
    }
}


AddStub200Response.OneOf = ["[String]"];

export default AddStub200Response;

