/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CallRecord model module.
 * @module model/CallRecord
 * @version 1.0.0
 */
class CallRecord {
    /**
     * Constructs a new <code>CallRecord</code>.
     * @alias module:model/CallRecord
     */
    constructor() { 
        
        CallRecord.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CallRecord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CallRecord} obj Optional instance to populate.
     * @return {module:model/CallRecord} The populated <code>CallRecord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CallRecord();

            if (data.hasOwnProperty('service')) {
                obj['service'] = ApiClient.convertToType(data['service'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('session')) {
                obj['session'] = ApiClient.convertToType(data['session'], 'String');
            }
            if (data.hasOwnProperty('stubId')) {
                obj['stubId'] = ApiClient.convertToType(data['stubId'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = ApiClient.convertToType(data['request'], {'String': Object});
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], [{'String': Object}]);
            }
            if (data.hasOwnProperty('response')) {
                obj['response'] = ApiClient.convertToType(data['response'], {'String': Object});
            }
            if (data.hasOwnProperty('responses')) {
                obj['responses'] = ApiClient.convertToType(data['responses'], [{'String': Object}]);
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CallRecord</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CallRecord</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['service'] && !(typeof data['service'] === 'string' || data['service'] instanceof String)) {
            throw new Error("Expected the field `service` to be a primitive type in the JSON string but got " + data['service']);
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }
        // ensure the json data is a string
        if (data['session'] && !(typeof data['session'] === 'string' || data['session'] instanceof String)) {
            throw new Error("Expected the field `session` to be a primitive type in the JSON string but got " + data['session']);
        }
        // ensure the json data is a string
        if (data['stubId'] && !(typeof data['stubId'] === 'string' || data['stubId'] instanceof String)) {
            throw new Error("Expected the field `stubId` to be a primitive type in the JSON string but got " + data['stubId']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['requests'])) {
            throw new Error("Expected the field `requests` to be an array in the JSON data but got " + data['requests']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['responses'])) {
            throw new Error("Expected the field `responses` to be an array in the JSON data but got " + data['responses']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}



/**
 * @member {String} service
 */
CallRecord.prototype['service'] = undefined;

/**
 * @member {String} method
 */
CallRecord.prototype['method'] = undefined;

/**
 * Session ID (empty = global)
 * @member {String} session
 */
CallRecord.prototype['session'] = undefined;

/**
 * Stub identifier
 * @member {String} stubId
 */
CallRecord.prototype['stubId'] = undefined;

/**
 * @member {Date} timestamp
 */
CallRecord.prototype['timestamp'] = undefined;

/**
 * Deprecated: use requests for streaming calls
 * @member {Object.<String, Object>} request
 */
CallRecord.prototype['request'] = undefined;

/**
 * Request messages for streaming calls (client stream, bidi stream)
 * @member {Array.<Object.<String, Object>>} requests
 */
CallRecord.prototype['requests'] = undefined;

/**
 * Deprecated: use responses for streaming calls
 * @member {Object.<String, Object>} response
 */
CallRecord.prototype['response'] = undefined;

/**
 * Response messages for streaming calls (server stream, bidi stream)
 * @member {Array.<Object.<String, Object>>} responses
 */
CallRecord.prototype['responses'] = undefined;

/**
 * gRPC status code (e.g., 0 for OK, 5 for NotFound)
 * @member {Number} code
 */
CallRecord.prototype['code'] = undefined;

/**
 * @member {String} error
 */
CallRecord.prototype['error'] = undefined;






export default CallRecord;

