/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DashboardOverview model module.
 * @module model/DashboardOverview
 * @version 1.0.0
 */
class DashboardOverview {
    /**
     * Constructs a new <code>DashboardOverview</code>.
     * @alias module:model/DashboardOverview
     * @param totalServices {Number} 
     * @param totalStubs {Number} 
     * @param usedStubs {Number} 
     * @param unusedStubs {Number} 
     * @param totalSessions {Number} 
     * @param runtimeDescriptors {Number} 
     * @param totalHistory {Number} 
     * @param historyErrors {Number} 
     */
    constructor(totalServices, totalStubs, usedStubs, unusedStubs, totalSessions, runtimeDescriptors, totalHistory, historyErrors) { 
        
        DashboardOverview.initialize(this, totalServices, totalStubs, usedStubs, unusedStubs, totalSessions, runtimeDescriptors, totalHistory, historyErrors);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, totalServices, totalStubs, usedStubs, unusedStubs, totalSessions, runtimeDescriptors, totalHistory, historyErrors) { 
        obj['totalServices'] = totalServices;
        obj['totalStubs'] = totalStubs;
        obj['usedStubs'] = usedStubs;
        obj['unusedStubs'] = unusedStubs;
        obj['totalSessions'] = totalSessions;
        obj['runtimeDescriptors'] = runtimeDescriptors;
        obj['totalHistory'] = totalHistory;
        obj['historyErrors'] = historyErrors;
    }

    /**
     * Constructs a <code>DashboardOverview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DashboardOverview} obj Optional instance to populate.
     * @return {module:model/DashboardOverview} The populated <code>DashboardOverview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DashboardOverview();

            if (data.hasOwnProperty('totalServices')) {
                obj['totalServices'] = ApiClient.convertToType(data['totalServices'], 'Number');
            }
            if (data.hasOwnProperty('totalStubs')) {
                obj['totalStubs'] = ApiClient.convertToType(data['totalStubs'], 'Number');
            }
            if (data.hasOwnProperty('usedStubs')) {
                obj['usedStubs'] = ApiClient.convertToType(data['usedStubs'], 'Number');
            }
            if (data.hasOwnProperty('unusedStubs')) {
                obj['unusedStubs'] = ApiClient.convertToType(data['unusedStubs'], 'Number');
            }
            if (data.hasOwnProperty('totalSessions')) {
                obj['totalSessions'] = ApiClient.convertToType(data['totalSessions'], 'Number');
            }
            if (data.hasOwnProperty('runtimeDescriptors')) {
                obj['runtimeDescriptors'] = ApiClient.convertToType(data['runtimeDescriptors'], 'Number');
            }
            if (data.hasOwnProperty('totalHistory')) {
                obj['totalHistory'] = ApiClient.convertToType(data['totalHistory'], 'Number');
            }
            if (data.hasOwnProperty('historyErrors')) {
                obj['historyErrors'] = ApiClient.convertToType(data['historyErrors'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DashboardOverview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DashboardOverview</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DashboardOverview.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

DashboardOverview.RequiredProperties = ["totalServices", "totalStubs", "usedStubs", "unusedStubs", "totalSessions", "runtimeDescriptors", "totalHistory", "historyErrors"];

/**
 * @member {Number} totalServices
 */
DashboardOverview.prototype['totalServices'] = undefined;

/**
 * @member {Number} totalStubs
 */
DashboardOverview.prototype['totalStubs'] = undefined;

/**
 * @member {Number} usedStubs
 */
DashboardOverview.prototype['usedStubs'] = undefined;

/**
 * @member {Number} unusedStubs
 */
DashboardOverview.prototype['unusedStubs'] = undefined;

/**
 * @member {Number} totalSessions
 */
DashboardOverview.prototype['totalSessions'] = undefined;

/**
 * @member {Number} runtimeDescriptors
 */
DashboardOverview.prototype['runtimeDescriptors'] = undefined;

/**
 * @member {Number} totalHistory
 */
DashboardOverview.prototype['totalHistory'] = undefined;

/**
 * @member {Number} historyErrors
 */
DashboardOverview.prototype['historyErrors'] = undefined;






export default DashboardOverview;

