/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Dashboard model module.
 * @module model/Dashboard
 * @version 1.0.0
 */
class Dashboard {
    /**
     * Constructs a new <code>Dashboard</code>.
     * @alias module:model/Dashboard
     * @param appName {String} 
     * @param version {String} 
     * @param goVersion {String} 
     * @param compiler {String} 
     * @param goos {String} 
     * @param goarch {String} 
     * @param numCPU {Number} 
     * @param startedAt {Date} 
     * @param uptimeSeconds {Number} 
     * @param ready {Boolean} 
     * @param historyEnabled {Boolean} 
     * @param totalServices {Number} 
     * @param totalStubs {Number} 
     * @param usedStubs {Number} 
     * @param unusedStubs {Number} 
     * @param totalSessions {Number} 
     * @param runtimeDescriptors {Number} 
     * @param totalHistory {Number} 
     * @param historyErrors {Number} 
     */
    constructor(appName, version, goVersion, compiler, goos, goarch, numCPU, startedAt, uptimeSeconds, ready, historyEnabled, totalServices, totalStubs, usedStubs, unusedStubs, totalSessions, runtimeDescriptors, totalHistory, historyErrors) { 
        
        Dashboard.initialize(this, appName, version, goVersion, compiler, goos, goarch, numCPU, startedAt, uptimeSeconds, ready, historyEnabled, totalServices, totalStubs, usedStubs, unusedStubs, totalSessions, runtimeDescriptors, totalHistory, historyErrors);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appName, version, goVersion, compiler, goos, goarch, numCPU, startedAt, uptimeSeconds, ready, historyEnabled, totalServices, totalStubs, usedStubs, unusedStubs, totalSessions, runtimeDescriptors, totalHistory, historyErrors) { 
        obj['appName'] = appName;
        obj['version'] = version;
        obj['goVersion'] = goVersion;
        obj['compiler'] = compiler;
        obj['goos'] = goos;
        obj['goarch'] = goarch;
        obj['numCPU'] = numCPU;
        obj['startedAt'] = startedAt;
        obj['uptimeSeconds'] = uptimeSeconds;
        obj['ready'] = ready;
        obj['historyEnabled'] = historyEnabled;
        obj['totalServices'] = totalServices;
        obj['totalStubs'] = totalStubs;
        obj['usedStubs'] = usedStubs;
        obj['unusedStubs'] = unusedStubs;
        obj['totalSessions'] = totalSessions;
        obj['runtimeDescriptors'] = runtimeDescriptors;
        obj['totalHistory'] = totalHistory;
        obj['historyErrors'] = historyErrors;
    }

    /**
     * Constructs a <code>Dashboard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Dashboard} obj Optional instance to populate.
     * @return {module:model/Dashboard} The populated <code>Dashboard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Dashboard();

            if (data.hasOwnProperty('appName')) {
                obj['appName'] = ApiClient.convertToType(data['appName'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('goVersion')) {
                obj['goVersion'] = ApiClient.convertToType(data['goVersion'], 'String');
            }
            if (data.hasOwnProperty('compiler')) {
                obj['compiler'] = ApiClient.convertToType(data['compiler'], 'String');
            }
            if (data.hasOwnProperty('goos')) {
                obj['goos'] = ApiClient.convertToType(data['goos'], 'String');
            }
            if (data.hasOwnProperty('goarch')) {
                obj['goarch'] = ApiClient.convertToType(data['goarch'], 'String');
            }
            if (data.hasOwnProperty('numCPU')) {
                obj['numCPU'] = ApiClient.convertToType(data['numCPU'], 'Number');
            }
            if (data.hasOwnProperty('startedAt')) {
                obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'Date');
            }
            if (data.hasOwnProperty('uptimeSeconds')) {
                obj['uptimeSeconds'] = ApiClient.convertToType(data['uptimeSeconds'], 'Number');
            }
            if (data.hasOwnProperty('ready')) {
                obj['ready'] = ApiClient.convertToType(data['ready'], 'Boolean');
            }
            if (data.hasOwnProperty('historyEnabled')) {
                obj['historyEnabled'] = ApiClient.convertToType(data['historyEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('totalServices')) {
                obj['totalServices'] = ApiClient.convertToType(data['totalServices'], 'Number');
            }
            if (data.hasOwnProperty('totalStubs')) {
                obj['totalStubs'] = ApiClient.convertToType(data['totalStubs'], 'Number');
            }
            if (data.hasOwnProperty('usedStubs')) {
                obj['usedStubs'] = ApiClient.convertToType(data['usedStubs'], 'Number');
            }
            if (data.hasOwnProperty('unusedStubs')) {
                obj['unusedStubs'] = ApiClient.convertToType(data['unusedStubs'], 'Number');
            }
            if (data.hasOwnProperty('totalSessions')) {
                obj['totalSessions'] = ApiClient.convertToType(data['totalSessions'], 'Number');
            }
            if (data.hasOwnProperty('runtimeDescriptors')) {
                obj['runtimeDescriptors'] = ApiClient.convertToType(data['runtimeDescriptors'], 'Number');
            }
            if (data.hasOwnProperty('totalHistory')) {
                obj['totalHistory'] = ApiClient.convertToType(data['totalHistory'], 'Number');
            }
            if (data.hasOwnProperty('historyErrors')) {
                obj['historyErrors'] = ApiClient.convertToType(data['historyErrors'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Dashboard</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Dashboard</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Dashboard.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['appName'] && !(typeof data['appName'] === 'string' || data['appName'] instanceof String)) {
            throw new Error("Expected the field `appName` to be a primitive type in the JSON string but got " + data['appName']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }
        // ensure the json data is a string
        if (data['goVersion'] && !(typeof data['goVersion'] === 'string' || data['goVersion'] instanceof String)) {
            throw new Error("Expected the field `goVersion` to be a primitive type in the JSON string but got " + data['goVersion']);
        }
        // ensure the json data is a string
        if (data['compiler'] && !(typeof data['compiler'] === 'string' || data['compiler'] instanceof String)) {
            throw new Error("Expected the field `compiler` to be a primitive type in the JSON string but got " + data['compiler']);
        }
        // ensure the json data is a string
        if (data['goos'] && !(typeof data['goos'] === 'string' || data['goos'] instanceof String)) {
            throw new Error("Expected the field `goos` to be a primitive type in the JSON string but got " + data['goos']);
        }
        // ensure the json data is a string
        if (data['goarch'] && !(typeof data['goarch'] === 'string' || data['goarch'] instanceof String)) {
            throw new Error("Expected the field `goarch` to be a primitive type in the JSON string but got " + data['goarch']);
        }

        return true;
    }


}

Dashboard.RequiredProperties = ["appName", "version", "goVersion", "compiler", "goos", "goarch", "numCPU", "startedAt", "uptimeSeconds", "ready", "historyEnabled", "totalServices", "totalStubs", "usedStubs", "unusedStubs", "totalSessions", "runtimeDescriptors", "totalHistory", "historyErrors"];

/**
 * @member {String} appName
 */
Dashboard.prototype['appName'] = undefined;

/**
 * @member {String} version
 */
Dashboard.prototype['version'] = undefined;

/**
 * @member {String} goVersion
 */
Dashboard.prototype['goVersion'] = undefined;

/**
 * @member {String} compiler
 */
Dashboard.prototype['compiler'] = undefined;

/**
 * @member {String} goos
 */
Dashboard.prototype['goos'] = undefined;

/**
 * @member {String} goarch
 */
Dashboard.prototype['goarch'] = undefined;

/**
 * @member {Number} numCPU
 */
Dashboard.prototype['numCPU'] = undefined;

/**
 * @member {Date} startedAt
 */
Dashboard.prototype['startedAt'] = undefined;

/**
 * @member {Number} uptimeSeconds
 */
Dashboard.prototype['uptimeSeconds'] = undefined;

/**
 * @member {Boolean} ready
 */
Dashboard.prototype['ready'] = undefined;

/**
 * @member {Boolean} historyEnabled
 */
Dashboard.prototype['historyEnabled'] = undefined;

/**
 * @member {Number} totalServices
 */
Dashboard.prototype['totalServices'] = undefined;

/**
 * @member {Number} totalStubs
 */
Dashboard.prototype['totalStubs'] = undefined;

/**
 * @member {Number} usedStubs
 */
Dashboard.prototype['usedStubs'] = undefined;

/**
 * @member {Number} unusedStubs
 */
Dashboard.prototype['unusedStubs'] = undefined;

/**
 * @member {Number} totalSessions
 */
Dashboard.prototype['totalSessions'] = undefined;

/**
 * @member {Number} runtimeDescriptors
 */
Dashboard.prototype['runtimeDescriptors'] = undefined;

/**
 * @member {Number} totalHistory
 */
Dashboard.prototype['totalHistory'] = undefined;

/**
 * @member {Number} historyErrors
 */
Dashboard.prototype['historyErrors'] = undefined;






export default Dashboard;

