/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DescriptorServiceIDs model module.
 * @module model/DescriptorServiceIDs
 * @version 1.0.0
 */
class DescriptorServiceIDs {
    /**
     * Constructs a new <code>DescriptorServiceIDs</code>.
     * @alias module:model/DescriptorServiceIDs
     * @param serviceIDs {Array.<String>} Service IDs added via POST /descriptors
     */
    constructor(serviceIDs) { 
        
        DescriptorServiceIDs.initialize(this, serviceIDs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, serviceIDs) { 
        obj['serviceIDs'] = serviceIDs;
    }

    /**
     * Constructs a <code>DescriptorServiceIDs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DescriptorServiceIDs} obj Optional instance to populate.
     * @return {module:model/DescriptorServiceIDs} The populated <code>DescriptorServiceIDs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DescriptorServiceIDs();

            if (data.hasOwnProperty('serviceIDs')) {
                obj['serviceIDs'] = ApiClient.convertToType(data['serviceIDs'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DescriptorServiceIDs</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DescriptorServiceIDs</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DescriptorServiceIDs.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['serviceIDs'])) {
            throw new Error("Expected the field `serviceIDs` to be an array in the JSON data but got " + data['serviceIDs']);
        }

        return true;
    }


}

DescriptorServiceIDs.RequiredProperties = ["serviceIDs"];

/**
 * Service IDs added via POST /descriptors
 * @member {Array.<String>} serviceIDs
 */
DescriptorServiceIDs.prototype['serviceIDs'] = undefined;






export default DescriptorServiceIDs;

