/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InspectRequest model module.
 * @module model/InspectRequest
 * @version 1.0.0
 */
class InspectRequest {
    /**
     * Constructs a new <code>InspectRequest</code>.
     * @alias module:model/InspectRequest
     * @param service {String} 
     * @param method {String} 
     */
    constructor(service, method) { 
        
        InspectRequest.initialize(this, service, method);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, service, method) { 
        obj['service'] = service;
        obj['method'] = method;
    }

    /**
     * Constructs a <code>InspectRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InspectRequest} obj Optional instance to populate.
     * @return {module:model/InspectRequest} The populated <code>InspectRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InspectRequest();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('service')) {
                obj['service'] = ApiClient.convertToType(data['service'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('session')) {
                obj['session'] = ApiClient.convertToType(data['session'], 'String');
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], {'String': Object});
            }
            if (data.hasOwnProperty('input')) {
                obj['input'] = ApiClient.convertToType(data['input'], [{'String': Object}]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InspectRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InspectRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InspectRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['service'] && !(typeof data['service'] === 'string' || data['service'] instanceof String)) {
            throw new Error("Expected the field `service` to be a primitive type in the JSON string but got " + data['service']);
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }
        // ensure the json data is a string
        if (data['session'] && !(typeof data['session'] === 'string' || data['session'] instanceof String)) {
            throw new Error("Expected the field `session` to be a primitive type in the JSON string but got " + data['session']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['input'])) {
            throw new Error("Expected the field `input` to be an array in the JSON data but got " + data['input']);
        }

        return true;
    }


}

InspectRequest.RequiredProperties = ["service", "method"];

/**
 * @member {String} id
 */
InspectRequest.prototype['id'] = undefined;

/**
 * @member {String} service
 */
InspectRequest.prototype['service'] = undefined;

/**
 * @member {String} method
 */
InspectRequest.prototype['method'] = undefined;

/**
 * @member {String} session
 */
InspectRequest.prototype['session'] = undefined;

/**
 * @member {Object.<String, Object>} headers
 */
InspectRequest.prototype['headers'] = undefined;

/**
 * @member {Array.<Object.<String, Object>>} input
 */
InspectRequest.prototype['input'] = undefined;






export default InspectRequest;

