/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InspectCandidate from './InspectCandidate';
import InspectStage from './InspectStage';

/**
 * The InspectReport model module.
 * @module model/InspectReport
 * @version 1.0.0
 */
class InspectReport {
    /**
     * Constructs a new <code>InspectReport</code>.
     * @alias module:model/InspectReport
     * @param service {String} 
     * @param method {String} 
     * @param session {String} 
     * @param matchedStubId {String} 
     * @param similarStubId {String} 
     * @param fallbackToMethod {Boolean} 
     * @param error {String} 
     * @param stages {Array.<module:model/InspectStage>} 
     * @param candidates {Array.<module:model/InspectCandidate>} 
     */
    constructor(service, method, session, matchedStubId, similarStubId, fallbackToMethod, error, stages, candidates) { 
        
        InspectReport.initialize(this, service, method, session, matchedStubId, similarStubId, fallbackToMethod, error, stages, candidates);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, service, method, session, matchedStubId, similarStubId, fallbackToMethod, error, stages, candidates) { 
        obj['service'] = service;
        obj['method'] = method;
        obj['session'] = session;
        obj['matchedStubId'] = matchedStubId;
        obj['similarStubId'] = similarStubId;
        obj['fallbackToMethod'] = fallbackToMethod;
        obj['error'] = error;
        obj['stages'] = stages;
        obj['candidates'] = candidates;
    }

    /**
     * Constructs a <code>InspectReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InspectReport} obj Optional instance to populate.
     * @return {module:model/InspectReport} The populated <code>InspectReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InspectReport();

            if (data.hasOwnProperty('service')) {
                obj['service'] = ApiClient.convertToType(data['service'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('session')) {
                obj['session'] = ApiClient.convertToType(data['session'], 'String');
            }
            if (data.hasOwnProperty('matchedStubId')) {
                obj['matchedStubId'] = ApiClient.convertToType(data['matchedStubId'], 'String');
            }
            if (data.hasOwnProperty('similarStubId')) {
                obj['similarStubId'] = ApiClient.convertToType(data['similarStubId'], 'String');
            }
            if (data.hasOwnProperty('fallbackToMethod')) {
                obj['fallbackToMethod'] = ApiClient.convertToType(data['fallbackToMethod'], 'Boolean');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('stages')) {
                obj['stages'] = ApiClient.convertToType(data['stages'], [InspectStage]);
            }
            if (data.hasOwnProperty('candidates')) {
                obj['candidates'] = ApiClient.convertToType(data['candidates'], [InspectCandidate]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InspectReport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InspectReport</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InspectReport.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['service'] && !(typeof data['service'] === 'string' || data['service'] instanceof String)) {
            throw new Error("Expected the field `service` to be a primitive type in the JSON string but got " + data['service']);
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }
        // ensure the json data is a string
        if (data['session'] && !(typeof data['session'] === 'string' || data['session'] instanceof String)) {
            throw new Error("Expected the field `session` to be a primitive type in the JSON string but got " + data['session']);
        }
        // ensure the json data is a string
        if (data['matchedStubId'] && !(typeof data['matchedStubId'] === 'string' || data['matchedStubId'] instanceof String)) {
            throw new Error("Expected the field `matchedStubId` to be a primitive type in the JSON string but got " + data['matchedStubId']);
        }
        // ensure the json data is a string
        if (data['similarStubId'] && !(typeof data['similarStubId'] === 'string' || data['similarStubId'] instanceof String)) {
            throw new Error("Expected the field `similarStubId` to be a primitive type in the JSON string but got " + data['similarStubId']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        if (data['stages']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['stages'])) {
                throw new Error("Expected the field `stages` to be an array in the JSON data but got " + data['stages']);
            }
            // validate the optional field `stages` (array)
            for (const item of data['stages']) {
                InspectStage.validateJSON(item);
            };
        }
        if (data['candidates']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['candidates'])) {
                throw new Error("Expected the field `candidates` to be an array in the JSON data but got " + data['candidates']);
            }
            // validate the optional field `candidates` (array)
            for (const item of data['candidates']) {
                InspectCandidate.validateJSON(item);
            };
        }

        return true;
    }


}

InspectReport.RequiredProperties = ["service", "method", "session", "matchedStubId", "similarStubId", "fallbackToMethod", "error", "stages", "candidates"];

/**
 * @member {String} service
 */
InspectReport.prototype['service'] = undefined;

/**
 * @member {String} method
 */
InspectReport.prototype['method'] = undefined;

/**
 * @member {String} session
 */
InspectReport.prototype['session'] = undefined;

/**
 * @member {String} matchedStubId
 */
InspectReport.prototype['matchedStubId'] = undefined;

/**
 * @member {String} similarStubId
 */
InspectReport.prototype['similarStubId'] = undefined;

/**
 * @member {Boolean} fallbackToMethod
 */
InspectReport.prototype['fallbackToMethod'] = undefined;

/**
 * @member {String} error
 */
InspectReport.prototype['error'] = undefined;

/**
 * @member {Array.<module:model/InspectStage>} stages
 */
InspectReport.prototype['stages'] = undefined;

/**
 * @member {Array.<module:model/InspectCandidate>} candidates
 */
InspectReport.prototype['candidates'] = undefined;






export default InspectReport;

