/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InspectCandidateEvent model module.
 * @module model/InspectCandidateEvent
 * @version 1.0.0
 */
class InspectCandidateEvent {
    /**
     * Constructs a new <code>InspectCandidateEvent</code>.
     * @alias module:model/InspectCandidateEvent
     * @param stage {String} 
     * @param result {String} 
     */
    constructor(stage, result) { 
        
        InspectCandidateEvent.initialize(this, stage, result);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, stage, result) { 
        obj['stage'] = stage;
        obj['result'] = result;
    }

    /**
     * Constructs a <code>InspectCandidateEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InspectCandidateEvent} obj Optional instance to populate.
     * @return {module:model/InspectCandidateEvent} The populated <code>InspectCandidateEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InspectCandidateEvent();

            if (data.hasOwnProperty('stage')) {
                obj['stage'] = ApiClient.convertToType(data['stage'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InspectCandidateEvent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InspectCandidateEvent</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InspectCandidateEvent.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['stage'] && !(typeof data['stage'] === 'string' || data['stage'] instanceof String)) {
            throw new Error("Expected the field `stage` to be a primitive type in the JSON string but got " + data['stage']);
        }
        // ensure the json data is a string
        if (data['result'] && !(typeof data['result'] === 'string' || data['result'] instanceof String)) {
            throw new Error("Expected the field `result` to be a primitive type in the JSON string but got " + data['result']);
        }
        // ensure the json data is a string
        if (data['reason'] && !(typeof data['reason'] === 'string' || data['reason'] instanceof String)) {
            throw new Error("Expected the field `reason` to be a primitive type in the JSON string but got " + data['reason']);
        }

        return true;
    }


}

InspectCandidateEvent.RequiredProperties = ["stage", "result"];

/**
 * @member {String} stage
 */
InspectCandidateEvent.prototype['stage'] = undefined;

/**
 * @member {String} result
 */
InspectCandidateEvent.prototype['result'] = undefined;

/**
 * @member {String} reason
 */
InspectCandidateEvent.prototype['reason'] = undefined;






export default InspectCandidateEvent;

