/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InspectStage model module.
 * @module model/InspectStage
 * @version 1.0.0
 */
class InspectStage {
    /**
     * Constructs a new <code>InspectStage</code>.
     * @alias module:model/InspectStage
     * @param name {String} 
     * @param before {Number} 
     * @param after {Number} 
     * @param removed {Number} 
     */
    constructor(name, before, after, removed) { 
        
        InspectStage.initialize(this, name, before, after, removed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, before, after, removed) { 
        obj['name'] = name;
        obj['before'] = before;
        obj['after'] = after;
        obj['removed'] = removed;
    }

    /**
     * Constructs a <code>InspectStage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InspectStage} obj Optional instance to populate.
     * @return {module:model/InspectStage} The populated <code>InspectStage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InspectStage();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('before')) {
                obj['before'] = ApiClient.convertToType(data['before'], 'Number');
            }
            if (data.hasOwnProperty('after')) {
                obj['after'] = ApiClient.convertToType(data['after'], 'Number');
            }
            if (data.hasOwnProperty('removed')) {
                obj['removed'] = ApiClient.convertToType(data['removed'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InspectStage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InspectStage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InspectStage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

InspectStage.RequiredProperties = ["name", "before", "after", "removed"];

/**
 * @member {String} name
 */
InspectStage.prototype['name'] = undefined;

/**
 * @member {Number} before
 */
InspectStage.prototype['before'] = undefined;

/**
 * @member {Number} after
 */
InspectStage.prototype['after'] = undefined;

/**
 * @member {Number} removed
 */
InspectStage.prototype['removed'] = undefined;






export default InspectStage;

