/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InspectCandidateEvent from './InspectCandidateEvent';

/**
 * The InspectCandidate model module.
 * @module model/InspectCandidate
 * @version 1.0.0
 */
class InspectCandidate {
    /**
     * Constructs a new <code>InspectCandidate</code>.
     * @alias module:model/InspectCandidate
     * @param id {String} 
     * @param service {String} 
     * @param method {String} 
     * @param session {String} 
     * @param priority {Number} 
     * @param times {Number} 
     * @param used {Number} 
     * @param specificity {Number} 
     * @param score {Number} 
     * @param visibleBySession {Boolean} 
     * @param withinTimes {Boolean} 
     * @param headersMatched {Boolean} 
     * @param inputMatched {Boolean} 
     * @param matched {Boolean} 
     * @param excludedBy {Array.<String>} 
     * @param events {Array.<module:model/InspectCandidateEvent>} 
     */
    constructor(id, service, method, session, priority, times, used, specificity, score, visibleBySession, withinTimes, headersMatched, inputMatched, matched, excludedBy, events) { 
        
        InspectCandidate.initialize(this, id, service, method, session, priority, times, used, specificity, score, visibleBySession, withinTimes, headersMatched, inputMatched, matched, excludedBy, events);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, service, method, session, priority, times, used, specificity, score, visibleBySession, withinTimes, headersMatched, inputMatched, matched, excludedBy, events) { 
        obj['id'] = id;
        obj['service'] = service;
        obj['method'] = method;
        obj['session'] = session;
        obj['priority'] = priority;
        obj['times'] = times;
        obj['used'] = used;
        obj['specificity'] = specificity;
        obj['score'] = score;
        obj['visibleBySession'] = visibleBySession;
        obj['withinTimes'] = withinTimes;
        obj['headersMatched'] = headersMatched;
        obj['inputMatched'] = inputMatched;
        obj['matched'] = matched;
        obj['excludedBy'] = excludedBy;
        obj['events'] = events;
    }

    /**
     * Constructs a <code>InspectCandidate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InspectCandidate} obj Optional instance to populate.
     * @return {module:model/InspectCandidate} The populated <code>InspectCandidate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InspectCandidate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('service')) {
                obj['service'] = ApiClient.convertToType(data['service'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('session')) {
                obj['session'] = ApiClient.convertToType(data['session'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('times')) {
                obj['times'] = ApiClient.convertToType(data['times'], 'Number');
            }
            if (data.hasOwnProperty('used')) {
                obj['used'] = ApiClient.convertToType(data['used'], 'Number');
            }
            if (data.hasOwnProperty('specificity')) {
                obj['specificity'] = ApiClient.convertToType(data['specificity'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('visibleBySession')) {
                obj['visibleBySession'] = ApiClient.convertToType(data['visibleBySession'], 'Boolean');
            }
            if (data.hasOwnProperty('withinTimes')) {
                obj['withinTimes'] = ApiClient.convertToType(data['withinTimes'], 'Boolean');
            }
            if (data.hasOwnProperty('headersMatched')) {
                obj['headersMatched'] = ApiClient.convertToType(data['headersMatched'], 'Boolean');
            }
            if (data.hasOwnProperty('inputMatched')) {
                obj['inputMatched'] = ApiClient.convertToType(data['inputMatched'], 'Boolean');
            }
            if (data.hasOwnProperty('matched')) {
                obj['matched'] = ApiClient.convertToType(data['matched'], 'Boolean');
            }
            if (data.hasOwnProperty('excludedBy')) {
                obj['excludedBy'] = ApiClient.convertToType(data['excludedBy'], ['String']);
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [InspectCandidateEvent]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InspectCandidate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InspectCandidate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InspectCandidate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['service'] && !(typeof data['service'] === 'string' || data['service'] instanceof String)) {
            throw new Error("Expected the field `service` to be a primitive type in the JSON string but got " + data['service']);
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }
        // ensure the json data is a string
        if (data['session'] && !(typeof data['session'] === 'string' || data['session'] instanceof String)) {
            throw new Error("Expected the field `session` to be a primitive type in the JSON string but got " + data['session']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['excludedBy'])) {
            throw new Error("Expected the field `excludedBy` to be an array in the JSON data but got " + data['excludedBy']);
        }
        if (data['events']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['events'])) {
                throw new Error("Expected the field `events` to be an array in the JSON data but got " + data['events']);
            }
            // validate the optional field `events` (array)
            for (const item of data['events']) {
                InspectCandidateEvent.validateJSON(item);
            };
        }

        return true;
    }


}

InspectCandidate.RequiredProperties = ["id", "service", "method", "session", "priority", "times", "used", "specificity", "score", "visibleBySession", "withinTimes", "headersMatched", "inputMatched", "matched", "excludedBy", "events"];

/**
 * @member {String} id
 */
InspectCandidate.prototype['id'] = undefined;

/**
 * @member {String} service
 */
InspectCandidate.prototype['service'] = undefined;

/**
 * @member {String} method
 */
InspectCandidate.prototype['method'] = undefined;

/**
 * @member {String} session
 */
InspectCandidate.prototype['session'] = undefined;

/**
 * @member {Number} priority
 */
InspectCandidate.prototype['priority'] = undefined;

/**
 * @member {Number} times
 */
InspectCandidate.prototype['times'] = undefined;

/**
 * @member {Number} used
 */
InspectCandidate.prototype['used'] = undefined;

/**
 * @member {Number} specificity
 */
InspectCandidate.prototype['specificity'] = undefined;

/**
 * @member {Number} score
 */
InspectCandidate.prototype['score'] = undefined;

/**
 * @member {Boolean} visibleBySession
 */
InspectCandidate.prototype['visibleBySession'] = undefined;

/**
 * @member {Boolean} withinTimes
 */
InspectCandidate.prototype['withinTimes'] = undefined;

/**
 * @member {Boolean} headersMatched
 */
InspectCandidate.prototype['headersMatched'] = undefined;

/**
 * @member {Boolean} inputMatched
 */
InspectCandidate.prototype['inputMatched'] = undefined;

/**
 * @member {Boolean} matched
 */
InspectCandidate.prototype['matched'] = undefined;

/**
 * @member {Array.<String>} excludedBy
 */
InspectCandidate.prototype['excludedBy'] = undefined;

/**
 * @member {Array.<module:model/InspectCandidateEvent>} events
 */
InspectCandidate.prototype['events'] = undefined;






export default InspectCandidate;

