/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import McpTool from './McpTool';
import McpTransport from './McpTransport';

/**
 * The McpInfoResponse model module.
 * @module model/McpInfoResponse
 * @version 1.0.0
 */
class McpInfoResponse {
    /**
     * Constructs a new <code>McpInfoResponse</code>.
     * @alias module:model/McpInfoResponse
     * @param protocolVersion {String} 
     * @param serverName {String} 
     * @param serverVersion {String} 
     * @param transport {module:model/McpTransport} 
     * @param methods {Array.<String>} 
     * @param tools {Array.<module:model/McpTool>} 
     */
    constructor(protocolVersion, serverName, serverVersion, transport, methods, tools) { 
        
        McpInfoResponse.initialize(this, protocolVersion, serverName, serverVersion, transport, methods, tools);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, protocolVersion, serverName, serverVersion, transport, methods, tools) { 
        obj['protocolVersion'] = protocolVersion;
        obj['serverName'] = serverName;
        obj['serverVersion'] = serverVersion;
        obj['transport'] = transport;
        obj['methods'] = methods;
        obj['tools'] = tools;
    }

    /**
     * Constructs a <code>McpInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/McpInfoResponse} obj Optional instance to populate.
     * @return {module:model/McpInfoResponse} The populated <code>McpInfoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new McpInfoResponse();

            if (data.hasOwnProperty('protocolVersion')) {
                obj['protocolVersion'] = ApiClient.convertToType(data['protocolVersion'], 'String');
            }
            if (data.hasOwnProperty('serverName')) {
                obj['serverName'] = ApiClient.convertToType(data['serverName'], 'String');
            }
            if (data.hasOwnProperty('serverVersion')) {
                obj['serverVersion'] = ApiClient.convertToType(data['serverVersion'], 'String');
            }
            if (data.hasOwnProperty('transport')) {
                obj['transport'] = McpTransport.constructFromObject(data['transport']);
            }
            if (data.hasOwnProperty('methods')) {
                obj['methods'] = ApiClient.convertToType(data['methods'], ['String']);
            }
            if (data.hasOwnProperty('tools')) {
                obj['tools'] = ApiClient.convertToType(data['tools'], [McpTool]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>McpInfoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>McpInfoResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of McpInfoResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['protocolVersion'] && !(typeof data['protocolVersion'] === 'string' || data['protocolVersion'] instanceof String)) {
            throw new Error("Expected the field `protocolVersion` to be a primitive type in the JSON string but got " + data['protocolVersion']);
        }
        // ensure the json data is a string
        if (data['serverName'] && !(typeof data['serverName'] === 'string' || data['serverName'] instanceof String)) {
            throw new Error("Expected the field `serverName` to be a primitive type in the JSON string but got " + data['serverName']);
        }
        // ensure the json data is a string
        if (data['serverVersion'] && !(typeof data['serverVersion'] === 'string' || data['serverVersion'] instanceof String)) {
            throw new Error("Expected the field `serverVersion` to be a primitive type in the JSON string but got " + data['serverVersion']);
        }
        // validate the optional field `transport`
        if (data['transport']) { // data not null
          McpTransport.validateJSON(data['transport']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['methods'])) {
            throw new Error("Expected the field `methods` to be an array in the JSON data but got " + data['methods']);
        }
        if (data['tools']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tools'])) {
                throw new Error("Expected the field `tools` to be an array in the JSON data but got " + data['tools']);
            }
            // validate the optional field `tools` (array)
            for (const item of data['tools']) {
                McpTool.validateJSON(item);
            };
        }

        return true;
    }


}

McpInfoResponse.RequiredProperties = ["protocolVersion", "serverName", "serverVersion", "transport", "methods", "tools"];

/**
 * @member {String} protocolVersion
 */
McpInfoResponse.prototype['protocolVersion'] = undefined;

/**
 * @member {String} serverName
 */
McpInfoResponse.prototype['serverName'] = undefined;

/**
 * @member {String} serverVersion
 */
McpInfoResponse.prototype['serverVersion'] = undefined;

/**
 * @member {module:model/McpTransport} transport
 */
McpInfoResponse.prototype['transport'] = undefined;

/**
 * @member {Array.<String>} methods
 */
McpInfoResponse.prototype['methods'] = undefined;

/**
 * @member {Array.<module:model/McpTool>} tools
 */
McpInfoResponse.prototype['tools'] = undefined;






export default McpInfoResponse;

