/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import McpID from './McpID';

/**
 * The McpRequest model module.
 * @module model/McpRequest
 * @version 1.0.0
 */
class McpRequest {
    /**
     * Constructs a new <code>McpRequest</code>.
     * @alias module:model/McpRequest
     * @param jsonrpc {String} 
     * @param method {String} 
     */
    constructor(jsonrpc, method) { 
        
        McpRequest.initialize(this, jsonrpc, method);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jsonrpc, method) { 
        obj['jsonrpc'] = jsonrpc;
        obj['method'] = method;
    }

    /**
     * Constructs a <code>McpRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/McpRequest} obj Optional instance to populate.
     * @return {module:model/McpRequest} The populated <code>McpRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new McpRequest();

            if (data.hasOwnProperty('jsonrpc')) {
                obj['jsonrpc'] = ApiClient.convertToType(data['jsonrpc'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = McpID.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>McpRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>McpRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of McpRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['jsonrpc'] && !(typeof data['jsonrpc'] === 'string' || data['jsonrpc'] instanceof String)) {
            throw new Error("Expected the field `jsonrpc` to be a primitive type in the JSON string but got " + data['jsonrpc']);
        }
        // validate the optional field `id`
        if (data['id']) { // data not null
          McpID.validateJSON(data['id']);
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }

        return true;
    }


}

McpRequest.RequiredProperties = ["jsonrpc", "method"];

/**
 * @member {String} jsonrpc
 */
McpRequest.prototype['jsonrpc'] = undefined;

/**
 * @member {module:model/McpID} id
 */
McpRequest.prototype['id'] = undefined;

/**
 * @member {String} method
 */
McpRequest.prototype['method'] = undefined;

/**
 * @member {Object.<String, Object>} params
 */
McpRequest.prototype['params'] = undefined;






export default McpRequest;

