/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import McpError from './McpError';
import McpID from './McpID';

/**
 * The McpResponse model module.
 * @module model/McpResponse
 * @version 1.0.0
 */
class McpResponse {
    /**
     * Constructs a new <code>McpResponse</code>.
     * @alias module:model/McpResponse
     * @param jsonrpc {String} 
     */
    constructor(jsonrpc) { 
        
        McpResponse.initialize(this, jsonrpc);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jsonrpc) { 
        obj['jsonrpc'] = jsonrpc;
    }

    /**
     * Constructs a <code>McpResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/McpResponse} obj Optional instance to populate.
     * @return {module:model/McpResponse} The populated <code>McpResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new McpResponse();

            if (data.hasOwnProperty('jsonrpc')) {
                obj['jsonrpc'] = ApiClient.convertToType(data['jsonrpc'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = McpID.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], {'String': Object});
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = McpError.constructFromObject(data['error']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>McpResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>McpResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of McpResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['jsonrpc'] && !(typeof data['jsonrpc'] === 'string' || data['jsonrpc'] instanceof String)) {
            throw new Error("Expected the field `jsonrpc` to be a primitive type in the JSON string but got " + data['jsonrpc']);
        }
        // validate the optional field `id`
        if (data['id']) { // data not null
          McpID.validateJSON(data['id']);
        }
        // validate the optional field `error`
        if (data['error']) { // data not null
          McpError.validateJSON(data['error']);
        }

        return true;
    }


}

McpResponse.RequiredProperties = ["jsonrpc"];

/**
 * @member {String} jsonrpc
 */
McpResponse.prototype['jsonrpc'] = undefined;

/**
 * @member {module:model/McpID} id
 */
McpResponse.prototype['id'] = undefined;

/**
 * @member {Object.<String, Object>} result
 */
McpResponse.prototype['result'] = undefined;

/**
 * @member {module:model/McpError} error
 */
McpResponse.prototype['error'] = undefined;






export default McpResponse;

