/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The McpTool model module.
 * @module model/McpTool
 * @version 1.0.0
 */
class McpTool {
    /**
     * Constructs a new <code>McpTool</code>.
     * @alias module:model/McpTool
     * @param name {String} 
     * @param description {String} 
     * @param inputSchema {Object.<String, Object>} 
     */
    constructor(name, description, inputSchema) { 
        
        McpTool.initialize(this, name, description, inputSchema);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description, inputSchema) { 
        obj['name'] = name;
        obj['description'] = description;
        obj['inputSchema'] = inputSchema;
    }

    /**
     * Constructs a <code>McpTool</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/McpTool} obj Optional instance to populate.
     * @return {module:model/McpTool} The populated <code>McpTool</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new McpTool();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('inputSchema')) {
                obj['inputSchema'] = ApiClient.convertToType(data['inputSchema'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>McpTool</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>McpTool</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of McpTool.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

McpTool.RequiredProperties = ["name", "description", "inputSchema"];

/**
 * @member {String} name
 */
McpTool.prototype['name'] = undefined;

/**
 * @member {String} description
 */
McpTool.prototype['description'] = undefined;

/**
 * @member {Object.<String, Object>} inputSchema
 */
McpTool.prototype['inputSchema'] = undefined;






export default McpTool;

