/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The McpTransport model module.
 * @module model/McpTransport
 * @version 1.0.0
 */
class McpTransport {
    /**
     * Constructs a new <code>McpTransport</code>.
     * @alias module:model/McpTransport
     * @param path {String} 
     * @param methods {Array.<String>} 
     */
    constructor(path, methods) { 
        
        McpTransport.initialize(this, path, methods);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, path, methods) { 
        obj['path'] = path;
        obj['methods'] = methods;
    }

    /**
     * Constructs a <code>McpTransport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/McpTransport} obj Optional instance to populate.
     * @return {module:model/McpTransport} The populated <code>McpTransport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new McpTransport();

            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('methods')) {
                obj['methods'] = ApiClient.convertToType(data['methods'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>McpTransport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>McpTransport</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of McpTransport.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['methods'])) {
            throw new Error("Expected the field `methods` to be an array in the JSON data but got " + data['methods']);
        }

        return true;
    }


}

McpTransport.RequiredProperties = ["path", "methods"];

/**
 * @member {String} path
 */
McpTransport.prototype['path'] = undefined;

/**
 * @member {Array.<String>} methods
 */
McpTransport.prototype['methods'] = undefined;






export default McpTransport;

