/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProtoMessageSchema from './ProtoMessageSchema';

/**
 * The Method model module.
 * @module model/Method
 * @version 1.0.0
 */
class Method {
    /**
     * Constructs a new <code>Method</code>.
     * @alias module:model/Method
     * @param id {String} 
     * @param name {String} 
     * @param methodType {module:model/Method.MethodTypeEnum} gRPC method interaction type
     */
    constructor(id, name, methodType) { 
        
        Method.initialize(this, id, name, methodType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, methodType) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['methodType'] = methodType;
    }

    /**
     * Constructs a <code>Method</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Method} obj Optional instance to populate.
     * @return {module:model/Method} The populated <code>Method</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Method();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('methodType')) {
                obj['methodType'] = ApiClient.convertToType(data['methodType'], 'String');
            }
            if (data.hasOwnProperty('requestType')) {
                obj['requestType'] = ApiClient.convertToType(data['requestType'], 'String');
            }
            if (data.hasOwnProperty('responseType')) {
                obj['responseType'] = ApiClient.convertToType(data['responseType'], 'String');
            }
            if (data.hasOwnProperty('requestSchema')) {
                obj['requestSchema'] = ProtoMessageSchema.constructFromObject(data['requestSchema']);
            }
            if (data.hasOwnProperty('responseSchema')) {
                obj['responseSchema'] = ProtoMessageSchema.constructFromObject(data['responseSchema']);
            }
            if (data.hasOwnProperty('clientStreaming')) {
                obj['clientStreaming'] = ApiClient.convertToType(data['clientStreaming'], 'Boolean');
            }
            if (data.hasOwnProperty('serverStreaming')) {
                obj['serverStreaming'] = ApiClient.convertToType(data['serverStreaming'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Method</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Method</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Method.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['methodType'] && !(typeof data['methodType'] === 'string' || data['methodType'] instanceof String)) {
            throw new Error("Expected the field `methodType` to be a primitive type in the JSON string but got " + data['methodType']);
        }
        // ensure the json data is a string
        if (data['requestType'] && !(typeof data['requestType'] === 'string' || data['requestType'] instanceof String)) {
            throw new Error("Expected the field `requestType` to be a primitive type in the JSON string but got " + data['requestType']);
        }
        // ensure the json data is a string
        if (data['responseType'] && !(typeof data['responseType'] === 'string' || data['responseType'] instanceof String)) {
            throw new Error("Expected the field `responseType` to be a primitive type in the JSON string but got " + data['responseType']);
        }
        // validate the optional field `requestSchema`
        if (data['requestSchema']) { // data not null
          ProtoMessageSchema.validateJSON(data['requestSchema']);
        }
        // validate the optional field `responseSchema`
        if (data['responseSchema']) { // data not null
          ProtoMessageSchema.validateJSON(data['responseSchema']);
        }

        return true;
    }


}

Method.RequiredProperties = ["id", "name", "methodType"];

/**
 * @member {String} id
 */
Method.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Method.prototype['name'] = undefined;

/**
 * gRPC method interaction type
 * @member {module:model/Method.MethodTypeEnum} methodType
 */
Method.prototype['methodType'] = undefined;

/**
 * Fully-qualified protobuf request message type
 * @member {String} requestType
 */
Method.prototype['requestType'] = undefined;

/**
 * Fully-qualified protobuf response message type
 * @member {String} responseType
 */
Method.prototype['responseType'] = undefined;

/**
 * @member {module:model/ProtoMessageSchema} requestSchema
 */
Method.prototype['requestSchema'] = undefined;

/**
 * @member {module:model/ProtoMessageSchema} responseSchema
 */
Method.prototype['responseSchema'] = undefined;

/**
 * Indicates client-side streaming method
 * @member {Boolean} clientStreaming
 */
Method.prototype['clientStreaming'] = undefined;

/**
 * Indicates server-side streaming method
 * @member {Boolean} serverStreaming
 */
Method.prototype['serverStreaming'] = undefined;





/**
 * Allowed values for the <code>methodType</code> property.
 * @enum {String}
 * @readonly
 */
Method['MethodTypeEnum'] = {

    /**
     * value: "unary"
     * @const
     */
    "unary": "unary",

    /**
     * value: "client_streaming"
     * @const
     */
    "client_streaming": "client_streaming",

    /**
     * value: "server_streaming"
     * @const
     */
    "server_streaming": "server_streaming",

    /**
     * value: "bidi_streaming"
     * @const
     */
    "bidi_streaming": "bidi_streaming"
};



export default Method;

