/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProtoFieldSchema from './ProtoFieldSchema';

/**
 * The ProtoMessageSchema model module.
 * @module model/ProtoMessageSchema
 * @version 1.0.0
 */
class ProtoMessageSchema {
    /**
     * Constructs a new <code>ProtoMessageSchema</code>.
     * @alias module:model/ProtoMessageSchema
     * @param typeName {String} Fully-qualified protobuf message type name
     * @param fields {Array.<module:model/ProtoFieldSchema>} 
     */
    constructor(typeName, fields) { 
        
        ProtoMessageSchema.initialize(this, typeName, fields);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, typeName, fields) { 
        obj['typeName'] = typeName;
        obj['fields'] = fields;
    }

    /**
     * Constructs a <code>ProtoMessageSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProtoMessageSchema} obj Optional instance to populate.
     * @return {module:model/ProtoMessageSchema} The populated <code>ProtoMessageSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProtoMessageSchema();

            if (data.hasOwnProperty('typeName')) {
                obj['typeName'] = ApiClient.convertToType(data['typeName'], 'String');
            }
            if (data.hasOwnProperty('recursiveRef')) {
                obj['recursiveRef'] = ApiClient.convertToType(data['recursiveRef'], 'Boolean');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [ProtoFieldSchema]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProtoMessageSchema</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProtoMessageSchema</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProtoMessageSchema.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['typeName'] && !(typeof data['typeName'] === 'string' || data['typeName'] instanceof String)) {
            throw new Error("Expected the field `typeName` to be a primitive type in the JSON string but got " + data['typeName']);
        }
        if (data['fields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['fields'])) {
                throw new Error("Expected the field `fields` to be an array in the JSON data but got " + data['fields']);
            }
            // validate the optional field `fields` (array)
            for (const item of data['fields']) {
                ProtoFieldSchema.validateJSON(item);
            };
        }

        return true;
    }


}

ProtoMessageSchema.RequiredProperties = ["typeName", "fields"];

/**
 * Fully-qualified protobuf message type name
 * @member {String} typeName
 */
ProtoMessageSchema.prototype['typeName'] = undefined;

/**
 * True when schema expansion stopped due to recursive reference
 * @member {Boolean} recursiveRef
 */
ProtoMessageSchema.prototype['recursiveRef'] = undefined;

/**
 * @member {Array.<module:model/ProtoFieldSchema>} fields
 */
ProtoMessageSchema.prototype['fields'] = undefined;






export default ProtoMessageSchema;

