/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProtoMessageSchema from './ProtoMessageSchema';

/**
 * The ProtoFieldSchema model module.
 * @module model/ProtoFieldSchema
 * @version 1.0.0
 */
class ProtoFieldSchema {
    /**
     * Constructs a new <code>ProtoFieldSchema</code>.
     * @alias module:model/ProtoFieldSchema
     * @param name {String} 
     * @param jsonName {String} 
     * @param number {Number} 
     * @param kind {String} 
     * @param cardinality {module:model/ProtoFieldSchema.CardinalityEnum} 
     */
    constructor(name, jsonName, number, kind, cardinality) { 
        
        ProtoFieldSchema.initialize(this, name, jsonName, number, kind, cardinality);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, jsonName, number, kind, cardinality) { 
        obj['name'] = name;
        obj['jsonName'] = jsonName;
        obj['number'] = number;
        obj['kind'] = kind;
        obj['cardinality'] = cardinality;
    }

    /**
     * Constructs a <code>ProtoFieldSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProtoFieldSchema} obj Optional instance to populate.
     * @return {module:model/ProtoFieldSchema} The populated <code>ProtoFieldSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProtoFieldSchema();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('jsonName')) {
                obj['jsonName'] = ApiClient.convertToType(data['jsonName'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('cardinality')) {
                obj['cardinality'] = ApiClient.convertToType(data['cardinality'], 'String');
            }
            if (data.hasOwnProperty('typeName')) {
                obj['typeName'] = ApiClient.convertToType(data['typeName'], 'String');
            }
            if (data.hasOwnProperty('oneof')) {
                obj['oneof'] = ApiClient.convertToType(data['oneof'], 'String');
            }
            if (data.hasOwnProperty('enumValues')) {
                obj['enumValues'] = ApiClient.convertToType(data['enumValues'], ['String']);
            }
            if (data.hasOwnProperty('map')) {
                obj['map'] = ApiClient.convertToType(data['map'], 'Boolean');
            }
            if (data.hasOwnProperty('mapKeyKind')) {
                obj['mapKeyKind'] = ApiClient.convertToType(data['mapKeyKind'], 'String');
            }
            if (data.hasOwnProperty('mapValueKind')) {
                obj['mapValueKind'] = ApiClient.convertToType(data['mapValueKind'], 'String');
            }
            if (data.hasOwnProperty('mapValueTypeName')) {
                obj['mapValueTypeName'] = ApiClient.convertToType(data['mapValueTypeName'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ProtoMessageSchema.constructFromObject(data['message']);
            }
            if (data.hasOwnProperty('mapValueMessage')) {
                obj['mapValueMessage'] = ProtoMessageSchema.constructFromObject(data['mapValueMessage']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProtoFieldSchema</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProtoFieldSchema</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProtoFieldSchema.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['jsonName'] && !(typeof data['jsonName'] === 'string' || data['jsonName'] instanceof String)) {
            throw new Error("Expected the field `jsonName` to be a primitive type in the JSON string but got " + data['jsonName']);
        }
        // ensure the json data is a string
        if (data['kind'] && !(typeof data['kind'] === 'string' || data['kind'] instanceof String)) {
            throw new Error("Expected the field `kind` to be a primitive type in the JSON string but got " + data['kind']);
        }
        // ensure the json data is a string
        if (data['cardinality'] && !(typeof data['cardinality'] === 'string' || data['cardinality'] instanceof String)) {
            throw new Error("Expected the field `cardinality` to be a primitive type in the JSON string but got " + data['cardinality']);
        }
        // ensure the json data is a string
        if (data['typeName'] && !(typeof data['typeName'] === 'string' || data['typeName'] instanceof String)) {
            throw new Error("Expected the field `typeName` to be a primitive type in the JSON string but got " + data['typeName']);
        }
        // ensure the json data is a string
        if (data['oneof'] && !(typeof data['oneof'] === 'string' || data['oneof'] instanceof String)) {
            throw new Error("Expected the field `oneof` to be a primitive type in the JSON string but got " + data['oneof']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['enumValues'])) {
            throw new Error("Expected the field `enumValues` to be an array in the JSON data but got " + data['enumValues']);
        }
        // ensure the json data is a string
        if (data['mapKeyKind'] && !(typeof data['mapKeyKind'] === 'string' || data['mapKeyKind'] instanceof String)) {
            throw new Error("Expected the field `mapKeyKind` to be a primitive type in the JSON string but got " + data['mapKeyKind']);
        }
        // ensure the json data is a string
        if (data['mapValueKind'] && !(typeof data['mapValueKind'] === 'string' || data['mapValueKind'] instanceof String)) {
            throw new Error("Expected the field `mapValueKind` to be a primitive type in the JSON string but got " + data['mapValueKind']);
        }
        // ensure the json data is a string
        if (data['mapValueTypeName'] && !(typeof data['mapValueTypeName'] === 'string' || data['mapValueTypeName'] instanceof String)) {
            throw new Error("Expected the field `mapValueTypeName` to be a primitive type in the JSON string but got " + data['mapValueTypeName']);
        }
        // validate the optional field `message`
        if (data['message']) { // data not null
          ProtoMessageSchema.validateJSON(data['message']);
        }
        // validate the optional field `mapValueMessage`
        if (data['mapValueMessage']) { // data not null
          ProtoMessageSchema.validateJSON(data['mapValueMessage']);
        }

        return true;
    }


}

ProtoFieldSchema.RequiredProperties = ["name", "jsonName", "number", "kind", "cardinality"];

/**
 * @member {String} name
 */
ProtoFieldSchema.prototype['name'] = undefined;

/**
 * @member {String} jsonName
 */
ProtoFieldSchema.prototype['jsonName'] = undefined;

/**
 * @member {Number} number
 */
ProtoFieldSchema.prototype['number'] = undefined;

/**
 * @member {String} kind
 */
ProtoFieldSchema.prototype['kind'] = undefined;

/**
 * @member {module:model/ProtoFieldSchema.CardinalityEnum} cardinality
 */
ProtoFieldSchema.prototype['cardinality'] = undefined;

/**
 * Referenced protobuf type for message/enum fields
 * @member {String} typeName
 */
ProtoFieldSchema.prototype['typeName'] = undefined;

/**
 * Oneof group name if field belongs to oneof
 * @member {String} oneof
 */
ProtoFieldSchema.prototype['oneof'] = undefined;

/**
 * @member {Array.<String>} enumValues
 */
ProtoFieldSchema.prototype['enumValues'] = undefined;

/**
 * @member {Boolean} map
 */
ProtoFieldSchema.prototype['map'] = undefined;

/**
 * @member {String} mapKeyKind
 */
ProtoFieldSchema.prototype['mapKeyKind'] = undefined;

/**
 * @member {String} mapValueKind
 */
ProtoFieldSchema.prototype['mapValueKind'] = undefined;

/**
 * @member {String} mapValueTypeName
 */
ProtoFieldSchema.prototype['mapValueTypeName'] = undefined;

/**
 * @member {module:model/ProtoMessageSchema} message
 */
ProtoFieldSchema.prototype['message'] = undefined;

/**
 * @member {module:model/ProtoMessageSchema} mapValueMessage
 */
ProtoFieldSchema.prototype['mapValueMessage'] = undefined;





/**
 * Allowed values for the <code>cardinality</code> property.
 * @enum {String}
 * @readonly
 */
ProtoFieldSchema['CardinalityEnum'] = {

    /**
     * value: "optional"
     * @const
     */
    "optional": "optional",

    /**
     * value: "required"
     * @const
     */
    "required": "required",

    /**
     * value: "repeated"
     * @const
     */
    "repeated": "repeated"
};



export default ProtoFieldSchema;

