/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Sessions model module.
 * @module model/Sessions
 * @version 1.0.0
 */
class Sessions {
    /**
     * Constructs a new <code>Sessions</code>.
     * @alias module:model/Sessions
     * @param sessions {Array.<String>} 
     */
    constructor(sessions) { 
        
        Sessions.initialize(this, sessions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sessions) { 
        obj['sessions'] = sessions;
    }

    /**
     * Constructs a <code>Sessions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Sessions} obj Optional instance to populate.
     * @return {module:model/Sessions} The populated <code>Sessions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sessions();

            if (data.hasOwnProperty('sessions')) {
                obj['sessions'] = ApiClient.convertToType(data['sessions'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Sessions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Sessions</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Sessions.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['sessions'])) {
            throw new Error("Expected the field `sessions` to be an array in the JSON data but got " + data['sessions']);
        }

        return true;
    }


}

Sessions.RequiredProperties = ["sessions"];

/**
 * @member {Array.<String>} sessions
 */
Sessions.prototype['sessions'] = undefined;






export default Sessions;

