/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StubHeadersAnyOfElement model module.
 * @module model/StubHeadersAnyOfElement
 * @version 1.0.0
 */
class StubHeadersAnyOfElement {
    /**
     * Constructs a new <code>StubHeadersAnyOfElement</code>.
     * @alias module:model/StubHeadersAnyOfElement
     */
    constructor() { 
        
        StubHeadersAnyOfElement.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StubHeadersAnyOfElement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StubHeadersAnyOfElement} obj Optional instance to populate.
     * @return {module:model/StubHeadersAnyOfElement} The populated <code>StubHeadersAnyOfElement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StubHeadersAnyOfElement();

            if (data.hasOwnProperty('equals')) {
                obj['equals'] = ApiClient.convertToType(data['equals'], {'String': 'String'});
            }
            if (data.hasOwnProperty('contains')) {
                obj['contains'] = ApiClient.convertToType(data['contains'], {'String': 'String'});
            }
            if (data.hasOwnProperty('matches')) {
                obj['matches'] = ApiClient.convertToType(data['matches'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StubHeadersAnyOfElement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StubHeadersAnyOfElement</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object.<String, String>} equals
 */
StubHeadersAnyOfElement.prototype['equals'] = undefined;

/**
 * @member {Object.<String, String>} contains
 */
StubHeadersAnyOfElement.prototype['contains'] = undefined;

/**
 * @member {Object.<String, String>} matches
 */
StubHeadersAnyOfElement.prototype['matches'] = undefined;






export default StubHeadersAnyOfElement;

