/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StubInputAnyOfElement model module.
 * @module model/StubInputAnyOfElement
 * @version 1.0.0
 */
class StubInputAnyOfElement {
    /**
     * Constructs a new <code>StubInputAnyOfElement</code>.
     * @alias module:model/StubInputAnyOfElement
     */
    constructor() { 
        
        StubInputAnyOfElement.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['ignoreArrayOrder'] = false;
    }

    /**
     * Constructs a <code>StubInputAnyOfElement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StubInputAnyOfElement} obj Optional instance to populate.
     * @return {module:model/StubInputAnyOfElement} The populated <code>StubInputAnyOfElement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StubInputAnyOfElement();

            if (data.hasOwnProperty('ignoreArrayOrder')) {
                obj['ignoreArrayOrder'] = ApiClient.convertToType(data['ignoreArrayOrder'], 'Boolean');
            }
            if (data.hasOwnProperty('equals')) {
                obj['equals'] = ApiClient.convertToType(data['equals'], {'String': Object});
            }
            if (data.hasOwnProperty('contains')) {
                obj['contains'] = ApiClient.convertToType(data['contains'], {'String': Object});
            }
            if (data.hasOwnProperty('matches')) {
                obj['matches'] = ApiClient.convertToType(data['matches'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StubInputAnyOfElement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StubInputAnyOfElement</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} ignoreArrayOrder
 * @default false
 */
StubInputAnyOfElement.prototype['ignoreArrayOrder'] = false;

/**
 * @member {Object.<String, Object>} equals
 */
StubInputAnyOfElement.prototype['equals'] = undefined;

/**
 * @member {Object.<String, Object>} contains
 */
StubInputAnyOfElement.prototype['contains'] = undefined;

/**
 * @member {Object.<String, Object>} matches
 */
StubInputAnyOfElement.prototype['matches'] = undefined;






export default StubInputAnyOfElement;

