/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StubEffect model module.
 * @module model/StubEffect
 * @version 1.0.0
 */
class StubEffect {
    /**
     * Constructs a new <code>StubEffect</code>.
     * @alias module:model/StubEffect
     * @param action {module:model/StubEffect.ActionEnum} 
     */
    constructor(action) { 
        
        StubEffect.initialize(this, action);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action) { 
        obj['action'] = action;
    }

    /**
     * Constructs a <code>StubEffect</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StubEffect} obj Optional instance to populate.
     * @return {module:model/StubEffect} The populated <code>StubEffect</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StubEffect();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('stub')) {
                obj['stub'] = ApiClient.convertToType(data['stub'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StubEffect</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StubEffect</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StubEffect.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

StubEffect.RequiredProperties = ["action"];

/**
 * @member {module:model/StubEffect.ActionEnum} action
 */
StubEffect.prototype['action'] = undefined;

/**
 * Stub UUID for delete action
 * @member {String} id
 */
StubEffect.prototype['id'] = undefined;

/**
 * Stub payload for upsert action
 * @member {Object.<String, Object>} stub
 */
StubEffect.prototype['stub'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
StubEffect['ActionEnum'] = {

    /**
     * value: "upsert"
     * @const
     */
    "upsert": "upsert",

    /**
     * value: "delete"
     * @const
     */
    "delete": "delete"
};



export default StubEffect;

