/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StubOutput model module.
 * @module model/StubOutput
 * @version 1.0.0
 */
class StubOutput {
    /**
     * Constructs a new <code>StubOutput</code>.
     * @alias module:model/StubOutput
     */
    constructor() { 
        
        StubOutput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StubOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StubOutput} obj Optional instance to populate.
     * @return {module:model/StubOutput} The populated <code>StubOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StubOutput();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], {'String': Object});
            }
            if (data.hasOwnProperty('stream')) {
                obj['stream'] = ApiClient.convertToType(data['stream'], [{'String': Object}]);
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], {'String': 'String'});
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ApiClient.convertToType(data['delay'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StubOutput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StubOutput</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['stream'])) {
            throw new Error("Expected the field `stream` to be an array in the JSON data but got " + data['stream']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // ensure the json data is a string
        if (data['delay'] && !(typeof data['delay'] === 'string' || data['delay'] instanceof String)) {
            throw new Error("Expected the field `delay` to be a primitive type in the JSON string but got " + data['delay']);
        }

        return true;
    }


}



/**
 * @member {Object.<String, Object>} data
 */
StubOutput.prototype['data'] = undefined;

/**
 * @member {Array.<Object.<String, Object>>} stream
 */
StubOutput.prototype['stream'] = undefined;

/**
 * @member {Object.<String, String>} headers
 */
StubOutput.prototype['headers'] = undefined;

/**
 * @member {String} error
 */
StubOutput.prototype['error'] = undefined;

/**
 * @member {Number} code
 */
StubOutput.prototype['code'] = undefined;

/**
 * Delay before sending the response
 * @member {String} delay
 */
StubOutput.prototype['delay'] = undefined;






export default StubOutput;

