/**
 * GripMock API Schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StubOutput model module.
 * @module model/StubOutput
 * @version 1.0.0
 */
class StubOutput {
    /**
     * Constructs a new <code>StubOutput</code>.
     * @alias module:model/StubOutput
     * @param data {Object.<String, Object>} 
     * @param error {String} 
     */
    constructor(data, error) { 
        
        StubOutput.initialize(this, data, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data, error) { 
        obj['data'] = data;
        obj['error'] = error;
    }

    /**
     * Constructs a <code>StubOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StubOutput} obj Optional instance to populate.
     * @return {module:model/StubOutput} The populated <code>StubOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StubOutput();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], {'String': Object});
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], {'String': 'String'});
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StubOutput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StubOutput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StubOutput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}

StubOutput.RequiredProperties = ["data", "error"];

/**
 * @member {Object.<String, Object>} data
 */
StubOutput.prototype['data'] = undefined;

/**
 * @member {Object.<String, String>} headers
 */
StubOutput.prototype['headers'] = undefined;

/**
 * @member {String} error
 */
StubOutput.prototype['error'] = undefined;

/**
 * @member {Number} code
 */
StubOutput.prototype['code'] = undefined;






export default StubOutput;

