/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StubOptions model module.
 * @module model/StubOptions
 * @version 1.0.0
 */
class StubOptions {
    /**
     * Constructs a new <code>StubOptions</code>.
     * Optional behavior settings for a stub
     * @alias module:model/StubOptions
     */
    constructor() { 
        
        StubOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['times'] = 0;
    }

    /**
     * Constructs a <code>StubOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StubOptions} obj Optional instance to populate.
     * @return {module:model/StubOptions} The populated <code>StubOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StubOptions();

            if (data.hasOwnProperty('times')) {
                obj['times'] = ApiClient.convertToType(data['times'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StubOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StubOptions</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Max number of matches; 0 = unlimited
 * @member {Number} times
 * @default 0
 */
StubOptions.prototype['times'] = 0;






export default StubOptions;

