/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StubOutputDetailsInner model module.
 * @module model/StubOutputDetailsInner
 * @version 1.0.0
 */
class StubOutputDetailsInner {
    /**
     * Constructs a new <code>StubOutputDetailsInner</code>.
     * @alias module:model/StubOutputDetailsInner
     * @extends Object
     * @param type {String} Full Any type URL (for example, type.googleapis.com/google.rpc.ErrorInfo)
     */
    constructor(type) { 
        
        StubOutputDetailsInner.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>StubOutputDetailsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StubOutputDetailsInner} obj Optional instance to populate.
     * @return {module:model/StubOutputDetailsInner} The populated <code>StubOutputDetailsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StubOutputDetailsInner();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StubOutputDetailsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StubOutputDetailsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StubOutputDetailsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

StubOutputDetailsInner.RequiredProperties = ["type"];

/**
 * Full Any type URL (for example, type.googleapis.com/google.rpc.ErrorInfo)
 * @member {String} type
 */
StubOutputDetailsInner.prototype['type'] = undefined;






export default StubOutputDetailsInner;

