/**
 * GripMock API Schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MessageOK from '../model/MessageOK';

/**
* Healthcheck service.
* @module api/HealthcheckApi
* @version 2.4.0
*/
export default class HealthcheckApi {

    /**
    * Constructs a new HealthcheckApi. 
    * @alias module:api/HealthcheckApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the liveness operation.
     * @callback module:api/HealthcheckApi~livenessCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessageOK} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Liveness check
     * The test says that the service is alive and yet
     * @param {module:api/HealthcheckApi~livenessCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessageOK}
     */
    liveness(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MessageOK;
      return this.apiClient.callApi(
        '/health/liveness', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the readiness operation.
     * @callback module:api/HealthcheckApi~readinessCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessageOK} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Readiness check
     * The test indicates readiness to receive traffic
     * @param {module:api/HealthcheckApi~readinessCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessageOK}
     */
    readiness(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MessageOK;
      return this.apiClient.callApi(
        '/health/readiness', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
