/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import McpInfoResponse from '../model/McpInfoResponse';
import McpRequest from '../model/McpRequest';
import McpResponse from '../model/McpResponse';

/**
* Mcp service.
* @module api/McpApi
* @version 1.0.0
*/
export default class McpApi {

    /**
    * Constructs a new McpApi. 
    * @alias module:api/McpApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * MCP transport metadata
     * Returns MCP server metadata, supported protocol versions and transport details.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/McpInfoResponse} and HTTP response
     */
    mcpInfoWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = McpInfoResponse;
      return this.apiClient.callApi(
        '/mcp', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * MCP transport metadata
     * Returns MCP server metadata, supported protocol versions and transport details.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/McpInfoResponse}
     */
    mcpInfo() {
      return this.mcpInfoWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * MCP JSON-RPC endpoint
     * Accepts MCP JSON-RPC requests (`initialize`, `ping`, `tools/list`, `tools/call`) and returns JSON-RPC responses.
     * @param {module:model/McpRequest} mcpRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/McpResponse} and HTTP response
     */
    mcpMessageWithHttpInfo(mcpRequest) {
      let postBody = mcpRequest;
      // verify the required parameter 'mcpRequest' is set
      if (mcpRequest === undefined || mcpRequest === null) {
        throw new Error("Missing the required parameter 'mcpRequest' when calling mcpMessage");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = McpResponse;
      return this.apiClient.callApi(
        '/mcp', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * MCP JSON-RPC endpoint
     * Accepts MCP JSON-RPC requests (`initialize`, `ping`, `tools/list`, `tools/call`) and returns JSON-RPC responses.
     * @param {module:model/McpRequest} mcpRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/McpResponse}
     */
    mcpMessage(mcpRequest) {
      return this.mcpMessageWithHttpInfo(mcpRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
