/**
 * GripMock API Schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddStub200Response from '../model/AddStub200Response';
import AddStubRequest from '../model/AddStubRequest';
import SearchRequest from '../model/SearchRequest';
import SearchResponse from '../model/SearchResponse';
import Stub from '../model/Stub';

/**
* Stubs service.
* @module api/StubsApi
* @version 2.4.0
*/
export default class StubsApi {

    /**
    * Constructs a new StubsApi. 
    * @alias module:api/StubsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addStub operation.
     * @callback module:api/StubsApi~addStubCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AddStub200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new stub to the store
     * Add a new stub to the store
     * @param {module:model/AddStubRequest} addStubRequest Create a new pet in the store
     * @param {module:api/StubsApi~addStubCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AddStub200Response}
     */
    addStub(addStubRequest, callback) {
      let postBody = addStubRequest;
      // verify the required parameter 'addStubRequest' is set
      if (addStubRequest === undefined || addStubRequest === null) {
        throw new Error("Missing the required parameter 'addStubRequest' when calling addStub");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AddStub200Response;
      return this.apiClient.callApi(
        '/stubs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the batchStubsDelete operation.
     * @callback module:api/StubsApi~batchStubsDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a pack by IDs
     * Takes IDs as input and deletes them
     * @param {Array.<String>} requestBody Create a new pet in the store
     * @param {module:api/StubsApi~batchStubsDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    batchStubsDelete(requestBody, callback) {
      let postBody = requestBody;
      // verify the required parameter 'requestBody' is set
      if (requestBody === undefined || requestBody === null) {
        throw new Error("Missing the required parameter 'requestBody' when calling batchStubsDelete");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/stubs/batchDelete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteStubByID operation.
     * @callback module:api/StubsApi~deleteStubByIDCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes stub by ID
     * The method removes the stub by ID
     * @param {String} uuid ID of stub
     * @param {module:api/StubsApi~deleteStubByIDCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteStubByID(uuid, callback) {
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling deleteStubByID");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/stubs/{uuid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listStubs operation.
     * @callback module:api/StubsApi~listStubsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Stub>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Getting a list of stubs
     * The list of stubs is required to view all added stubs
     * @param {module:api/StubsApi~listStubsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Stub>}
     */
    listStubs(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Stub];
      return this.apiClient.callApi(
        '/stubs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listUnusedStubs operation.
     * @callback module:api/StubsApi~listUnusedStubsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Stub>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Getting a list of unused stubs
     * The list is needed to quickly find unused stubs
     * @param {module:api/StubsApi~listUnusedStubsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Stub>}
     */
    listUnusedStubs(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Stub];
      return this.apiClient.callApi(
        '/stubs/unused', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listUsedStubs operation.
     * @callback module:api/StubsApi~listUsedStubsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Stub>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Getting a list of used stubs
     * The list is needed to quickly find used stubs
     * @param {module:api/StubsApi~listUsedStubsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Stub>}
     */
    listUsedStubs(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Stub];
      return this.apiClient.callApi(
        '/stubs/used', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the purgeStubs operation.
     * @callback module:api/StubsApi~purgeStubsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove all stubs
     * Completely clears the stub storage
     * @param {module:api/StubsApi~purgeStubsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    purgeStubs(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/stubs', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchStubs operation.
     * @callback module:api/StubsApi~searchStubsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SearchResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Stub storage search
     * Performs a search for a stub by the given conditions
     * @param {module:model/SearchRequest} searchRequest Description of filtering
     * @param {module:api/StubsApi~searchStubsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SearchResponse}
     */
    searchStubs(searchRequest, callback) {
      let postBody = searchRequest;
      // verify the required parameter 'searchRequest' is set
      if (searchRequest === undefined || searchRequest === null) {
        throw new Error("Missing the required parameter 'searchRequest' when calling searchStubs");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SearchResponse;
      return this.apiClient.callApi(
        '/stubs/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
