/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MessageOK from '../model/MessageOK';
import VerifyError from '../model/VerifyError';
import VerifyRequest from '../model/VerifyRequest';

/**
* Verify service.
* @module api/VerifyApi
* @version 1.0.0
*/
export default class VerifyApi {

    /**
    * Constructs a new VerifyApi. 
    * @alias module:api/VerifyApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Verify call counts
     * Asserts that a method was called a specified number of times
     * @param {module:model/VerifyRequest} verifyRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MessageOK} and HTTP response
     */
    verifyCallsWithHttpInfo(verifyRequest) {
      let postBody = verifyRequest;
      // verify the required parameter 'verifyRequest' is set
      if (verifyRequest === undefined || verifyRequest === null) {
        throw new Error("Missing the required parameter 'verifyRequest' when calling verifyCalls");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = MessageOK;
      return this.apiClient.callApi(
        '/verify', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Verify call counts
     * Asserts that a method was called a specified number of times
     * @param {module:model/VerifyRequest} verifyRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MessageOK}
     */
    verifyCalls(verifyRequest) {
      return this.verifyCallsWithHttpInfo(verifyRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
