/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GripmockSdk);
  }
}(this, function(expect, GripmockSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GripmockSdk.DashboardOverview();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DashboardOverview', function() {
    it('should create an instance of DashboardOverview', function() {
      // uncomment below and update the code to test DashboardOverview
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be.a(GripmockSdk.DashboardOverview);
    });

    it('should have the property totalServices (base name: "totalServices")', function() {
      // uncomment below and update the code to test the property totalServices
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be();
    });

    it('should have the property totalStubs (base name: "totalStubs")', function() {
      // uncomment below and update the code to test the property totalStubs
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be();
    });

    it('should have the property usedStubs (base name: "usedStubs")', function() {
      // uncomment below and update the code to test the property usedStubs
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be();
    });

    it('should have the property unusedStubs (base name: "unusedStubs")', function() {
      // uncomment below and update the code to test the property unusedStubs
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be();
    });

    it('should have the property totalSessions (base name: "totalSessions")', function() {
      // uncomment below and update the code to test the property totalSessions
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be();
    });

    it('should have the property runtimeDescriptors (base name: "runtimeDescriptors")', function() {
      // uncomment below and update the code to test the property runtimeDescriptors
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be();
    });

    it('should have the property totalHistory (base name: "totalHistory")', function() {
      // uncomment below and update the code to test the property totalHistory
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be();
    });

    it('should have the property historyErrors (base name: "historyErrors")', function() {
      // uncomment below and update the code to test the property historyErrors
      //var instance = new GripmockSdk.DashboardOverview();
      //expect(instance).to.be();
    });

  });

}));
