/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GripmockSdk);
  }
}(this, function(expect, GripmockSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GripmockSdk.DashboardInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DashboardInfo', function() {
    it('should create an instance of DashboardInfo', function() {
      // uncomment below and update the code to test DashboardInfo
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be.a(GripmockSdk.DashboardInfo);
    });

    it('should have the property appName (base name: "appName")', function() {
      // uncomment below and update the code to test the property appName
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property goVersion (base name: "goVersion")', function() {
      // uncomment below and update the code to test the property goVersion
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property compiler (base name: "compiler")', function() {
      // uncomment below and update the code to test the property compiler
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property goos (base name: "goos")', function() {
      // uncomment below and update the code to test the property goos
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property goarch (base name: "goarch")', function() {
      // uncomment below and update the code to test the property goarch
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property numCPU (base name: "numCPU")', function() {
      // uncomment below and update the code to test the property numCPU
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property startedAt (base name: "startedAt")', function() {
      // uncomment below and update the code to test the property startedAt
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property uptimeSeconds (base name: "uptimeSeconds")', function() {
      // uncomment below and update the code to test the property uptimeSeconds
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property ready (base name: "ready")', function() {
      // uncomment below and update the code to test the property ready
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property historyEnabled (base name: "historyEnabled")', function() {
      // uncomment below and update the code to test the property historyEnabled
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property totalServices (base name: "totalServices")', function() {
      // uncomment below and update the code to test the property totalServices
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property totalStubs (base name: "totalStubs")', function() {
      // uncomment below and update the code to test the property totalStubs
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property totalSessions (base name: "totalSessions")', function() {
      // uncomment below and update the code to test the property totalSessions
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

    it('should have the property runtimeDescriptors (base name: "runtimeDescriptors")', function() {
      // uncomment below and update the code to test the property runtimeDescriptors
      //var instance = new GripmockSdk.DashboardInfo();
      //expect(instance).to.be();
    });

  });

}));
