/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GripmockSdk);
  }
}(this, function(expect, GripmockSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GripmockSdk.InspectReport();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InspectReport', function() {
    it('should create an instance of InspectReport', function() {
      // uncomment below and update the code to test InspectReport
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be.a(GripmockSdk.InspectReport);
    });

    it('should have the property service (base name: "service")', function() {
      // uncomment below and update the code to test the property service
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

    it('should have the property method (base name: "method")', function() {
      // uncomment below and update the code to test the property method
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

    it('should have the property session (base name: "session")', function() {
      // uncomment below and update the code to test the property session
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

    it('should have the property matchedStubId (base name: "matchedStubId")', function() {
      // uncomment below and update the code to test the property matchedStubId
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

    it('should have the property similarStubId (base name: "similarStubId")', function() {
      // uncomment below and update the code to test the property similarStubId
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

    it('should have the property fallbackToMethod (base name: "fallbackToMethod")', function() {
      // uncomment below and update the code to test the property fallbackToMethod
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

    it('should have the property stages (base name: "stages")', function() {
      // uncomment below and update the code to test the property stages
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

    it('should have the property candidates (base name: "candidates")', function() {
      // uncomment below and update the code to test the property candidates
      //var instance = new GripmockSdk.InspectReport();
      //expect(instance).to.be();
    });

  });

}));
