/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GripmockSdk);
  }
}(this, function(expect, GripmockSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GripmockSdk.InspectCandidate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InspectCandidate', function() {
    it('should create an instance of InspectCandidate', function() {
      // uncomment below and update the code to test InspectCandidate
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be.a(GripmockSdk.InspectCandidate);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property service (base name: "service")', function() {
      // uncomment below and update the code to test the property service
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property method (base name: "method")', function() {
      // uncomment below and update the code to test the property method
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property session (base name: "session")', function() {
      // uncomment below and update the code to test the property session
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property priority (base name: "priority")', function() {
      // uncomment below and update the code to test the property priority
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property times (base name: "times")', function() {
      // uncomment below and update the code to test the property times
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property used (base name: "used")', function() {
      // uncomment below and update the code to test the property used
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property specificity (base name: "specificity")', function() {
      // uncomment below and update the code to test the property specificity
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property visibleBySession (base name: "visibleBySession")', function() {
      // uncomment below and update the code to test the property visibleBySession
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property withinTimes (base name: "withinTimes")', function() {
      // uncomment below and update the code to test the property withinTimes
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property headersMatched (base name: "headersMatched")', function() {
      // uncomment below and update the code to test the property headersMatched
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property inputMatched (base name: "inputMatched")', function() {
      // uncomment below and update the code to test the property inputMatched
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property matched (base name: "matched")', function() {
      // uncomment below and update the code to test the property matched
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property excludedBy (base name: "excludedBy")', function() {
      // uncomment below and update the code to test the property excludedBy
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

    it('should have the property events (base name: "events")', function() {
      // uncomment below and update the code to test the property events
      //var instance = new GripmockSdk.InspectCandidate();
      //expect(instance).to.be();
    });

  });

}));
