/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GripmockSdk);
  }
}(this, function(expect, GripmockSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GripmockSdk.ProtoFieldSchema();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProtoFieldSchema', function() {
    it('should create an instance of ProtoFieldSchema', function() {
      // uncomment below and update the code to test ProtoFieldSchema
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be.a(GripmockSdk.ProtoFieldSchema);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property jsonName (base name: "jsonName")', function() {
      // uncomment below and update the code to test the property jsonName
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property number (base name: "number")', function() {
      // uncomment below and update the code to test the property number
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property kind (base name: "kind")', function() {
      // uncomment below and update the code to test the property kind
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property cardinality (base name: "cardinality")', function() {
      // uncomment below and update the code to test the property cardinality
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property typeName (base name: "typeName")', function() {
      // uncomment below and update the code to test the property typeName
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property oneof (base name: "oneof")', function() {
      // uncomment below and update the code to test the property oneof
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property enumValues (base name: "enumValues")', function() {
      // uncomment below and update the code to test the property enumValues
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property map (base name: "map")', function() {
      // uncomment below and update the code to test the property map
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property mapKeyKind (base name: "mapKeyKind")', function() {
      // uncomment below and update the code to test the property mapKeyKind
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property mapValueKind (base name: "mapValueKind")', function() {
      // uncomment below and update the code to test the property mapValueKind
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property mapValueTypeName (base name: "mapValueTypeName")', function() {
      // uncomment below and update the code to test the property mapValueTypeName
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

    it('should have the property mapValueMessage (base name: "mapValueMessage")', function() {
      // uncomment below and update the code to test the property mapValueMessage
      //var instance = new GripmockSdk.ProtoFieldSchema();
      //expect(instance).to.be();
    });

  });

}));
