/**
 * GripMock API Schema
 * Documentation and API specification GripMock.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GripmockSdk);
  }
}(this, function(expect, GripmockSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GripmockSdk.VerifyError();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VerifyError', function() {
    it('should create an instance of VerifyError', function() {
      // uncomment below and update the code to test VerifyError
      //var instance = new GripmockSdk.VerifyError();
      //expect(instance).to.be.a(GripmockSdk.VerifyError);
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new GripmockSdk.VerifyError();
      //expect(instance).to.be();
    });

    it('should have the property expected (base name: "expected")', function() {
      // uncomment below and update the code to test the property expected
      //var instance = new GripmockSdk.VerifyError();
      //expect(instance).to.be();
    });

    it('should have the property actual (base name: "actual")', function() {
      // uncomment below and update the code to test the property actual
      //var instance = new GripmockSdk.VerifyError();
      //expect(instance).to.be();
    });

  });

}));
