/**
 * GripMock API Schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GripmockSdkJs);
  }
}(this, function(expect, GripmockSdkJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GripmockSdkJs.StubsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StubsApi', function() {
    describe('addStub', function() {
      it('should call addStub successfully', function(done) {
        //uncomment below and update the code to test addStub
        //instance.addStub(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchStubsDelete', function() {
      it('should call batchStubsDelete successfully', function(done) {
        //uncomment below and update the code to test batchStubsDelete
        //instance.batchStubsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteStubByID', function() {
      it('should call deleteStubByID successfully', function(done) {
        //uncomment below and update the code to test deleteStubByID
        //instance.deleteStubByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listStubs', function() {
      it('should call listStubs successfully', function(done) {
        //uncomment below and update the code to test listStubs
        //instance.listStubs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUnusedStubs', function() {
      it('should call listUnusedStubs successfully', function(done) {
        //uncomment below and update the code to test listUnusedStubs
        //instance.listUnusedStubs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUsedStubs', function() {
      it('should call listUsedStubs successfully', function(done) {
        //uncomment below and update the code to test listUsedStubs
        //instance.listUsedStubs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('purgeStubs', function() {
      it('should call purgeStubs successfully', function(done) {
        //uncomment below and update the code to test purgeStubs
        //instance.purgeStubs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchStubs', function() {
      it('should call searchStubs successfully', function(done) {
        //uncomment below and update the code to test searchStubs
        //instance.searchStubs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
